### ISSUE TITLE
Permissions issue on hieradata directory w/ vagrant

### ISSUE THREAD

**Issue by mmarseglia** [hunner/puppet-hiera#114]
When hieradata is located within the puppet-control repo permissions cannot be set on the shared vagrant folder within the VM.

[root@master modules]# puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for master.vagrant.vm
Info: Applying configuration version '1454621749'
Error: Failed to set owner to '494': Operation not permitted @ lchown_internal - /vagrant/hieradata
Error: /Stage[main]/Hiera/File[/vagrant/hieradata]/owner: change from vagrant to pe-puppet failed: Failed to set owner to '494': Operation not permitted @ lchown_internal - /vagrant/hieradata
Error: Failed to set group to '495': Operation not permitted @ lchown_internal - /vagrant/hieradata
Error: /Stage[main]/Hiera/File[/vagrant/hieradata]/group: change from vagrant to pe-puppet failed: Failed to set group to '495': Operation not permitted @ lchown_internal - /vagrant/hieradata
Notice: /Stage[main]/Puppet_enterprise::Master::Puppetserver/Service[pe-puppetserver]: Dependency File[/vagrant/hieradata] has failures: true
Warning: /Stage[main]/Puppet_enterprise::Master::Puppetserver/Service[pe-puppetserver]: Skipping because of failed dependencies
Notice: Applied catalog in 9.35 seconds

ws-marsegm:puppet-control marsegm$ tree -L 2
.
├── Puppetfile
├── Readme.md
├── Vagrantfile
├── environment.conf
├── hieradata
│   ├── domain
│   ├── global.yaml
│   ├── nodes
│   └── tier
├── hooks
│   ├── commit_hooks
│   ├── pre-commit
│   └── pre-receive
├── manifests
│   └── site.pp
├── pe-install.txt
├── provision
│   ├── config
│   └── ssh
├── reference
│   └── Puppet\ Code\ Promotion\ Workflow.jpeg
└── site
    ├── profiles
    └── roles

**Comment by hunner** [comment]
Pass `datadir_manage => false` to the base hiera class and it won't try to adjust the permissions.
