### ISSUE TITLE
ReadMe incorrect with regards master_service

### ISSUE THREAD

**Issue by snesbittsea** [hunner/puppet-hiera#122]
Current readme indicates that the one needs to set the hiera::parameters::masterservice parameter in order to enable restart of puppetserver. 

Based on the code this is incorrect. The parameter is master_service (note underscore) and the settings is hiera::master_service

**Comment by hunner** [comment]
Fixed in https://github.com/hunner/puppet-hiera/pull/121 . Thanks!
