### ISSUE TITLE
manage hiera gem|package?

### ISSUE THREAD

**Issue by igalic** [hunner/puppet-hiera#20]
I use puppetlabs-operations to install puppet-agent|master, but I use this module (as per their recommendation) to manage hiera.

However, this module does *not* install hiera, that is, of course, because hiera has been a puppet dependency since 3.0.

Now the problem comes with trying to keep the infrastructure puppet-wise current: puppetlabs-operations puppet module has `ensure=>latest`, but only for puppet agent/master, this does not cascade down to their dependencies, and so hiera (and facter) are stuck at super old versions.

What's the best solution to that "problem"?

**Comment by jyaworski** [comment]
We are now managing the hiera package.

**Comment by hunner** [comment]
@jyaworski ++
