### ISSUE TITLE
Add support for puppet 3.7 (puppetserver)

### ISSUE THREAD

**Issue by mlehner616** [hunner/puppet-hiera#46]
This module doesn't install the hiera-eyaml gem correctly on the new-ish puppet 3.7. This requires us to manually run the following command or work around it with an exec resource.

`puppetserver gem install hiera-eyaml`

**Comment by igalic** [comment]
is there a specific check we can do to see if we're dealing with puppetserver?

**Comment by elyscape** [comment]
Not directly, but you can cheat:
```puppet
$on_puppetserver = (inline_template('<%= RUBY_PLATFORM =>') == 'java')
```

**Comment by elyscape** [comment]
Also note that, while there is a `rubyplatform` fact, you cannot use it for this as it returns the Ruby platform that Facter and the Puppet agent run on, not the Puppet master.

**Comment by hunner** [comment]
#45 and #58 essentially try to solve this, but not perfectly. I'm going to close the issue in preference for an actual PR.
