### ISSUE TITLE
eyaml datadir

### ISSUE THREAD

**Issue by ahuffman** [hunner/puppet-hiera#61]
I used the datadir => '/var/lib/hiera' parameter, and the eyaml => true parameter.  I was expecting all the datadirs to be the same, but in the hiera.yaml it has /etc/puppet/hieradata as the eyaml datadir:

:yaml:
   :datadir: /var/lib/hiera

:eyaml:
   :datadir: /etc/puppet/hieradata

Is there a way to specify the eyaml datadir, and/or is keeping eyaml intermixed with normal yaml good/bad?

**Comment by ahuffman** [comment]
Nevermind, I RTFM.  eyaml_datadir looks like it should do it, although your documentation says it defaults to the datadir option:

"eyaml_datadir
The path to the directory where hiera will look for databases with the eyaml backend.
Default: same as datadir"

**Comment by rnelson0** [comment]
It is confusing. Does it mean that eyaml_datadir defaults to the same value as datadir, or that it defaults to $datadir? Clearly the result is not $datadir, but was that the intention?

**Comment by ahuffman** [comment]
The documentation definitely needs to be clarified, but when I went digging, the default from the hiera module's params.pp is /etc/puppet/hieradata for both datadir and eyaml_datadir.  If you don't specify a datadir, the module will use /etc/puppet/hieradata.

Here's the config I ended up using, and it is working great.

 #Hiera Configuration
  class {'::hiera':
    hierarchy => [
      'secure',
      '%{clientcert}',
      'common',
    ],
    eyaml                   => true,
    eyaml_datadir      => '/var/lib/hiera',
    logger                   => 'console',
    merge_behavior   => 'deeper',
    datadir                  => '/var/lib/hiera',
  }
