### ISSUE TITLE
Merge configuration, gem not installed by hiera module

### ISSUE THREAD

**Issue by ahuffman** [hunner/puppet-hiera#62]
Any chance the  merge_behavior => 'deeper' parameter can manage the gem install as well?  It's already being done on the eyaml-hiera gem...

/var/log/httpd/error_log
App 552 stderr: WARN: Thu Apr 09 10:39:33 -0400 2015: Ignoring configured merge_behavior
App 552 stderr: WARN: Thu Apr 09 10:39:33 -0400 2015: Must have 'deep_merge' gem installed.

**Comment by hunner** [comment]
This has been merged now.
