### ISSUE TITLE
versioncmp expects a string value

### ISSUE THREAD

**Issue by bwilcox** [hunner/puppet-hiera#95]
In a new installation of PE 2015.3 I ran into the following error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef at /etc/puppetlabs/code/environments/production/modules/hiera/manifests/params.pp:43:8 on node

I created a pull request for the fix I'm using from my local copy.

**Comment by hunner** [comment]
Closed in #98
